### ISSUE TITLE
Dataset labelling

### ISSUE THREAD

**Issue by thanhsang298** [ndcuong91/MC_OCR#10]
Hi anh, 
Cảm ơn anh đã chia sẻ process rất hay ạ. Em có 1 chút thắc mắc do không thể tải được trực tiếp bộ dataset. Cuộc thi chỉ yêu cầu trích xuất 4 trường thông tin trên hóa đơn, vậy lúc label task recognition thì không biết BTC có label các ảnh crop của các trường khác không ạ?
Em cảm ơn anh :D

**Comment by ndcuong91** [comment]
BTC chỉ label ảnh crop của 4 trường thông tin trên hóa đơn thôi em nhé, thế nên các solution đều sử dụng open source cho phần text recognition

**Comment by thanhsang298** [comment]
em cảm ơn anh đã thông tin ạ
