### ISSUE TITLE
Minor feedback

### ISSUE THREAD

**Issue by anhtienng** [ndcuong91/MC_OCR#2]
Cảm ơn anh @ndcuong91 và team đã chia sẻ solution rất hay tới mọi người !

Em xin có 2 góp ý nhỏ sau:
- Weight của mô hình VietOCR là config Transformer, không phải là Seq2Seq như trong file README.
- Anh có thể thêm file paper vào repo được không ạ ? 

_Cảm ơn anh !_

**Comment by ndcuong91** [comment]
Cảm ơn em đã góp ý, cái weight anh sẽ check lại còn cái paper khi nào được public officially thì anh sẽ thêm vào repo nhé.
