### ISSUE TITLE
Trích xuất hình ảnh hóa đơn ra khỏi background

### ISSUE THREAD

**Issue by suonbo** [ndcuong91/MC_OCR#3]
Ở hình minh họa các bước Training, mình thấy hình ảnh của background hình như được crop ra khỏi background đúng không nhỉ.
![image](https://user-images.githubusercontent.com/87938340/145741032-a25a4c82-6067-4ba2-87d0-3b47a1352702.png)
Cho mình hỏi nếu có bước crop giấy ra khỏi background thì nhóm đã áp dụng phương pháp nào vậy ạ

**Comment by ndcuong91** [comment]
Hi bạn, hình ảnh chỉ mang tính minh hoạ chứ bên mình ko crop ảnh hóa đơn ra nhé.

**Comment by suonbo** [comment]
Cảm ơn bạn nhé
