### ISSUE TITLE
Hỏi về dataset của cuộc thi!

### ISSUE THREAD

**Issue by tiensu** [ndcuong91/MC_OCR#4]
Hiện tại cuộc thi đã hết hạn, mình không thể đăng ký để tải dataset được. Bạn có thể gửi link down cho mình được không? Cảm ơn bạn!

**Comment by ndcuong91** [comment]
Chào bạn, cuộc thi vẫn open tại đây nhé https://aihub.vn/competitions/1 . Bạn đăng ký xong là sẽ download được dataset
