### ISSUE TITLE
[Confidence score] Xin giải đáp về confidence score của PICK model

### ISSUE THREAD

**Issue by thanhpt93** [ndcuong91/MC_OCR#6]
Chào tác giả!
Rất cảm ơn tác giả đã chia sẻ repo cho mọi người.
Mình hiện tại cũng đang thử train model PICK và cũng đã ra được model. Nhưng khi predict thì mình không nhận được confidence score cho các class tương ứng. Không biết là tác giả có thể chỉ ra cho mình được không?
Mong nhận được sự giúp đỡ từ tác giả.
Xin cảm ơn.

**Comment by noinh** [comment]
bạn cho mình xin đường dẫn tải dataset với, mình tìm mà ko thấy

**Comment by thanhpt93** [comment]
@noinh data mình sử dụng là data khác nhé b

**Comment by ndcuong91** [comment]
> Chào tác giả! Rất cảm ơn tác giả đã chia sẻ repo cho mọi người. Mình hiện tại cũng đang thử train model PICK và cũng đã ra được model. Nhưng khi predict thì mình không nhận được confidence score cho các class tương ứng. Không biết là tác giả có thể chỉ ra cho mình được không? Mong nhận được sự giúp đỡ từ tác giả. Xin cảm ơn.

Có thể đây là cái bạn cần: https://github.com/wenwenyu/PICK-pytorch/issues/28
