### ISSUE TITLE
Text line rotate 

### ISSUE THREAD

**Issue by NguyenThaiHoc1** [ndcuong91/MC_OCR#8]
Chào anh. 

Anh cho em hỏi trong hình luồng xử lý em thấy có phần "Text line rotate" em có lục trong code nhưng không thấy anh giúp hiểu thêm được không? 

em cảm ơn anh

**Comment by ndcuong91** [comment]
@NguyenThaiHoc1 Trong flow sẽ có bước rotate lại bounding box nhận được từ phần text detection xong mới cho vào text recognition nhé. em đọc thêm ở hàm rotate_and_crop tại [đây](https://github.com/ndcuong91/MC_OCR/blob/d656f687264434c6c6c9b46e52ee4dcaa7d13863/mc_ocr/rotation_corrector/utils/line_angle_correction.py#L1)
