### ISSUE TITLE
Form của  Anno_path trong process_mc_ocr_data.py 

### ISSUE THREAD

**Issue by ntquyen11** [ndcuong91/MC_OCR#9]
Anh cho em hỏi file txt của anno_path ở đây, coordinates có cấu trúc như thế nào ạ 
![image](https://user-images.githubusercontent.com/73950718/184082822-ffefb4ab-a9aa-44b3-a585-4965fca54326.png)

**Comment by ndcuong91** [comment]
Ví dụ như này nhé:
```
72,25,326,25,326,64,72,64,TAN WOON YANN
50,82,440,82,440,121,50,121,BOOK TA .K(TAMAN DAYA) SDN BND
205,121,285,121,285,139,205,139,789417-W
110,144,383,144,383,163,110,163,NO.53 55,57 & 59, JALAN SAGU 18,
192,169,299,169,299,187,192,187,TAMAN DAYA,
```
Đây là format thường dùng trong cuộc thi của ICDAR đó em

**Comment by ntquyen11** [comment]
Hi a Cương,
Em cảm ơn a đã respone to issue ạ, a cho e hỏi ý nghĩa của các tham số kia
ạ tại vì e làm custom dataset.

Vào Th 5, 11 thg 8, 2022 lúc 16:08 Nguyễn Duy Cương <
***@***.***> đã viết:

**Comment by ndcuong91** [comment]
![image](https://user-images.githubusercontent.com/17918935/184576048-01e6d853-b854-46a9-82b0-3fc77200d81f.png)

vd với ảnh này, box màu đỏ có nhãn là "cat" thì annotation sẽ là:
```
98,345,420,345,420,462,98,462,cat
```
tương ứng với
```
(left,top,right,top,right,bottom,left,bottom,label)
```

**Comment by ntquyen11** [comment]
Hi anh,

Em hiểu r ạ. Em cảm ơn a nhiều ạ!

Vào Th 2, 15 thg 8, 2022 lúc 11:19 Nguyễn Duy Cương <
***@***.***> đã viết:
